WIP: feat: add support for initContainer in dev mode
devspace-sh/devspace pull request #2397
Opened 2022-10-31 08:14 UTC by pratikjagrut

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind feature

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #2360 

**Please provide a short message that should be published in the DevSpace release notes**
Fixed an issue where DevSpace ...

**What else do we need to know?**

2022-11-03 13:49 UTC, lizardruss requested changes
In general this looks good. I would like to reduce code duplication, if it's possible without hurting readability.

Also some testing, either unit or e2e. At least one happy path where everything works as expected, and one where there's issues with the init container.

2022-11-03 13:49 UTC, lizardruss commented on pkg/devspace/devpod/devpod.go
> +		}
Maybe reduce duplication by extracting a `targetSelector` var.

2022-11-03 13:49 UTC, lizardruss commented on pkg/devspace/devpod/devpod.go
> +				}
Could reduce duplication by extracting a `containers` var

2022-11-03 13:49 UTC, lizardruss commented on pkg/devspace/devpod/devpod.go
> +
Was it not possible to modify the existing waiting strategy?

2022-11-03 13:49 UTC, lizardruss commented on pkg/devspace/services/targetselector/until_init_container_running.go
> +}
The other implementation reports pod problems. What does the behavior of this have when there is an image pull backoff for the init container, or if it's in a crash loop?

2022-12-12 00:33 UTC, alexandrem commented
Is there anyone still working on this?

This is a blocking issue for me and I'm interested in this fix.

2022-12-12 00:33 UTC, alexandrem commented
Is there anyone still working on this?

This is a blocking issue for me and I'm interested in this fix.

2022-12-15 15:40 UTC, FabianKramm commented
@alexandrem since this is impacting a lot of areas in DevSpace, we have postponed the change

2023-01-30 08:56 UTC, closed without merging